site_name: SLS数据加工(DSL) Docs
theme: readthedocs
nav:
    - '介绍': 'index.md'
    - '快速入门': 'quick_start.md'
    - '快速参考': 'cheetsheet.md'
    - '最佳实践':
        - '常见日志处理':
            - 'Nginx日志加工处理': 'best_practices/nginx/parse_nginx.md'
            - 'Syslog日志加工处理': 'best_practices/syslog/parse_syslog.md'
        - '日志分发':
            - '跨区域传输Logstore' : 'best_practices/data_flow/cross_region.md'
            - '复制Logstore数据': 'best_practices/copy_logstore/copy_logstore_data.md'
            - '多源Logstore数据汇总': 'best_practices/summary_logstore/summary_logstore_data.md'
            - '复制和分发数据': 'best_practices/split_data/split_data_and_output.md'
            - '多目标logstore数据分发': 'best_practices/output_logstore/output_logstore_data.md'
        - '数据富化':
            - '数据加工富化整体介绍': 'best_practices/resource/data_join.md'
            - '用Logstore做富化': 'best_practices/logstore_join/pull_logstore_data.md'
            - '用OSS做数据富化': 'best_practices/oss/parse_oss_csv.md'
            #- '用RDS MySQL数据富化': 'best_practices/rds_mysql/pull_rds_mysql.md'
            - '用RDS做数据富化': 'best_practices/rds_mysql_vpc/pull_rds_mysql_vpc.md'
            - '用字典做数据富化': 'best_practices/dict_table/make_dict_table.md'
            #- '使用e_dict_map、e_search_dict_map函数进行数据富化': 'best_practices/table/use_table_join.md'
        - 'IP地址相关':
            - '使用ipip库解析ip地址': 'best_practices/ipip/geo_parse_ipip.md'
            - '使用ip2location解析ip地址': 'best_practices/ip2location/oss_ip2location.md'
            - 'Flowlog流量过滤': 'best_practices/flowlog/filter_flow.md'
            - '调用函数清洗数据': 'best_practices/function/use_func.md'
           # - '事件判断': 'best_practices/event/event_judgment.md'
        - '特定格式处理':
            - '数据脱敏': 'best_practices/remove_sensitive_info/data.md'
            - '日期时间格式处理': 'best_practices/datetime/datetime.md'
            - '字符串键值对动态提取': 'best_practices/string/parse_string_kv.md'
            - '特定格式文本数据加工': 'best_practices/text/text_transform.md'
            - 'JSON格式处理': 'best_practices/json/json_parse.md'
            - 'CSV格式处理': 'best_practices/csv/parse_csv.md'
            - 'Log转Metric': 'best_practices/log2metric/log2metric.md'
    
