site_name: SLS数据加工(DSL) Docs
theme: readthedocs
nav:
    - '介绍': 'index.md'
    - '快速入门': 'quick_start.md'
    - '快速参考': 'cheetsheet.md'
    - '最佳实践':
        - 'Nginx日志解析': 'best_practices/nginx/parse_nginx.md'
        - 'Flowlog流量过滤': 'best_practices/flowlog/filter_flow.md'
